; Runtime copy of the port signature on the first BAT row below the 20-row
; C64 playfield. Also redraw the top-left commit id bank-safely: debug_room.asm
; stores the seven nibbles in banked .data, so direct absolute LDA can read the
; wrong ROM bank after the project grew. Mapping the data explicitly fixes the
; observed 0000000/1111... garbage while preserving the existing glyph set.

DEBUG_FOOTER_VISIBLE_BAT = 23*BAT_LINE

.code

debug_footer_visible_draw:
        lda     #<DEBUG_FOOTER_VISIBLE_BAT
        sta     <_di
        lda     #>DEBUG_FOOTER_VISIBLE_BAT
        sta     <_di+1
        call    vdc_di_to_mawr
        ldx     #0
.loop:
        lda     debug_footer_tiles,x
        clc
        adc     #DEBUG_HEX_CHR
        sta     VDC_DL
        lda     #$70
        sta     VDC_DH
        inx
        cpx     #18
        bne     .loop
        jmp     debug_commit_bank_safe_draw

; build_commit_nibbles is an incbin generated by build.sh. Always map its bank
; before reading it; never assume the current code/data bank matches.
debug_commit_bank_safe_draw:
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     #<build_commit_nibbles
        sta     <_bp
        lda     #>build_commit_nibbles
        sta     <_bp+1
        ldy     #BANK(build_commit_nibbles)
        call    map_bp_to_mpr34

        lda     #<DEBUG_COMMIT_BAT
        sta     <_di
        lda     #>DEBUG_COMMIT_BAT
        sta     <_di+1
        call    vdc_di_to_mawr

        cly
.commit_loop:
        lda     [_bp],y
        clc
        adc     #DEBUG_HEX_CHR
        sta     VDC_DL
        lda     #$70
        sta     VDC_DH
        iny
        cpy     #7
        bne     .commit_loop

        pla
        tam4
        pla
        tam3
        plp
        rts
