; Persistent debug/build overlay.
; Top-left: 7-digit Git commit id generated by build.sh.
; Top-right: current room id as two hexadecimal digits.
; Bottom-left: fixed port signature "A thE rZA PCE port".
; Uses only the reserved diagnostic-font VRAM region below CHR_GAME.
;
; IMPORTANT: debug_footer_visible.asm is the single bank-safe writer for the
; commit id and footer. Keeping duplicate writers here previously wasted code
; space and could overwrite the visible commit row. debug_room_draw now owns
; only the room id at top-right.

DEBUG_COMMIT_BAT = 0
DEBUG_ROOM_BAT   = 38
DEBUG_FOOTER_BAT = 27*BAT_LINE
DEBUG_HEX_CHR    = CHR_FONT

.code

debug_room_init:
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     #<debug_overlay_patterns
        sta     <_bp
        lda     #>debug_overlay_patterns
        sta     <_bp+1
        ldy     #BANK(debug_overlay_patterns)
        call    map_bp_to_mpr34

        lda     #<(DEBUG_HEX_CHR*16)
        sta     <_di
        lda     #>(DEBUG_HEX_CHR*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ; 32 glyphs * 32 bytes = 1024 bytes = four 256-byte pages.
        ldx     #4
        cly
.page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .page
        inc     <_bp+1
        dex
        bne     .page

        pla
        tam4
        pla
        tam3
        plp

        jmp     debug_room_draw

; Draw only the room id. Commit id and footer are deliberately owned by
; debug_footer_visible.asm, which remaps their banked data before reading it.
debug_room_draw:
        lda     #<DEBUG_ROOM_BAT
        sta     <_di
        lda     #>DEBUG_ROOM_BAT
        sta     <_di+1
        call    vdc_di_to_mawr

        lda     <monty_room
        lsr     a
        lsr     a
        lsr     a
        lsr     a
        clc
        adc     #DEBUG_HEX_CHR
        sta     VDC_DL
        lda     #$70
        sta     VDC_DH

        lda     <monty_room
        and     #$0f
        clc
        adc     #DEBUG_HEX_CHR
        sta     VDC_DL
        lda     #$70
        sta     VDC_DH
        rts

.data
; Generated by build.sh from the current repository HEAD. Each byte is one
; hexadecimal nibble (0..15), allowing the ROM to identify its exact source.
build_commit_nibbles:
        incbin  "build-commit.dat"

; Tile offsets spelling exactly: A thE rZA PCE port
; 0..15 are hexadecimal 0-F, then 16=space, 17=t, 18=h, 19=r,
; 20=Z, 21=P, 22=p, 23=o.
debug_footer_tiles:
        db $0a,$10,$11,$12,$0e,$10,$13,$14,$0a,$10,$15,$0c,$0e,$10,$16,$17,$13,$11

; 8x8 1bpp glyphs converted to PCE 4bpp tiles. Each source row is plane 0
; followed by zero plane 1; planes 2/3 are zero. The complete block is padded
; to 32 glyphs (1024 bytes), making the bank-safe upload loop page-aligned.
debug_overlay_patterns:
        ; 0
        db $3c,$00,$66,$00,$6e,$00,$76,$00,$66,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; 1
        db $18,$00,$38,$00,$18,$00,$18,$00,$18,$00,$18,$00,$7e,$00,$00,$00
        ds 16,0
        ; 2
        db $3c,$00,$66,$00,$06,$00,$0c,$00,$30,$00,$60,$00,$7e,$00,$00,$00
        ds 16,0
        ; 3
        db $3c,$00,$66,$00,$06,$00,$1c,$00,$06,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; 4
        db $0c,$00,$1c,$00,$3c,$00,$6c,$00,$7e,$00,$0c,$00,$0c,$00,$00,$00
        ds 16,0
        ; 5
        db $7e,$00,$60,$00,$7c,$00,$06,$00,$06,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; 6
        db $1c,$00,$30,$00,$60,$00,$7c,$00,$66,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; 7
        db $7e,$00,$66,$00,$0c,$00,$18,$00,$18,$00,$18,$00,$18,$00,$00,$00
        ds 16,0
        ; 8
        db $3c,$00,$66,$00,$66,$00,$3c,$00,$66,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; 9
        db $3c,$00,$66,$00,$66,$00,$3e,$00,$06,$00,$0c,$00,$38,$00,$00,$00
        ds 16,0
        ; A
        db $18,$00,$3c,$00,$66,$00,$66,$00,$7e,$00,$66,$00,$66,$00,$00,$00
        ds 16,0
        ; B
        db $7c,$00,$66,$00,$66,$00,$7c,$00,$66,$00,$66,$00,$7c,$00,$00,$00
        ds 16,0
        ; C
        db $3c,$00,$66,$00,$60,$00,$60,$00,$60,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; D
        db $78,$00,$6c,$00,$66,$00,$66,$00,$66,$00,$6c,$00,$78,$00,$00,$00
        ds 16,0
        ; E
        db $7e,$00,$60,$00,$60,$00,$7c,$00,$60,$00,$60,$00,$7e,$00,$00,$00
        ds 16,0
        ; F
        db $7e,$00,$60,$00,$60,$00,$7c,$00,$60,$00,$60,$00,$60,$00,$00,$00
        ds 16,0
        ; space
        ds 32,0
        ; t
        db $18,$00,$18,$00,$7e,$00,$18,$00,$18,$00,$18,$00,$0e,$00,$00,$00
        ds 16,0
        ; h
        db $60,$00,$60,$00,$7c,$00,$66,$00,$66,$00,$66,$00,$66,$00,$00,$00
        ds 16,0
        ; r
        db $00,$00,$00,$00,$6c,$00,$76,$00,$60,$00,$60,$00,$60,$00,$00,$00
        ds 16,0
        ; Z
        db $7e,$00,$06,$00,$0c,$00,$18,$00,$30,$00,$60,$00,$7e,$00,$00,$00
        ds 16,0
        ; P
        db $7c,$00,$66,$00,$66,$00,$7c,$00,$60,$00,$60,$00,$60,$00,$00,$00
        ds 16,0
        ; p
        db $00,$00,$00,$00,$7c,$00,$66,$00,$66,$00,$7c,$00,$60,$00,$60,$00
        ds 16,0
        ; o
        db $00,$00,$00,$00,$3c,$00,$66,$00,$66,$00,$66,$00,$3c,$00,$00,$00
        ds 16,0
        ; glyphs 24..31 reserved
        ds 256,0
