; Exact Room $0A decor upload: 24 chars generated by tools/room0a_decor.py.
CHR_ROOM0A_DECOR = CHR_GAME + 9

.code
.proc room0a_upload_decor
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     #<room0a_decor_patterns
        sta     <_bp
        lda     #>room0a_decor_patterns
        sta     <_bp+1
        ldy     #BANK(room0a_decor_patterns)
        call    map_bp_to_mpr34

        lda     #<(CHR_ROOM0A_DECOR*16)
        sta     <_di
        lda     #>(CHR_ROOM0A_DECOR*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ; 24 chars * 32 bytes = 768 bytes = 3 pages.
        ldx     #3
.page:
        cly
.copy_page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .copy_page
        inc     <_bp+1
        dex
        bne     .page

        pla
        tam4
        pla
        tam3
        plp
        leave
.endp
