; Phase 36: bank-safe Room $01 decor upload.
; The exact C64 decor bitmaps are generated by tools/room01_decor.py.
; They occupy 25 8x8 PCE background characters immediately after chars 0..8.

CHR_ROOM01_DECOR = CHR_GAME + 9

.code

room01_upload_decor:
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     #<room01_decor_patterns
        sta     <_bp
        lda     #>room01_decor_patterns
        sta     <_bp+1
        ldy     #BANK(room01_decor_patterns)
        call    map_bp_to_mpr34

        lda     #<(CHR_ROOM01_DECOR*16)
        sta     <_di
        lda     #>(CHR_ROOM01_DECOR*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ; 25 chars * 32 bytes = 800 bytes = 3 full pages + 32 bytes.
        ldx     #3
.page:
        cly
.copy_page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .copy_page
        inc     <_bp+1
        dex
        bne     .page

        ; Final 32 bytes = 16 VDC words.
        cly
        ldx     #16
.tail:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        dex
        bne     .tail

        pla
        tam4
        pla
        tam3
        plp
        rts
