; Bank-safe decor upload for hexadecimal Rooms $20-$33 that contain original
; Decor.room_list objects. BAT placement is generated by rooms20_33_decor.py.

.bss
room20_33_decor_index: ds 1

.code
.proc room20_33_upload_decor
        lda     <world_pending_room
        ldx     #0
.find:
        cmp     .room_ids,x
        beq     .found
        inx
        cpx     #17
        bne     .find
        leave

.found:
        stx     room20_33_decor_index
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     .src_lo,x
        sta     <_bp
        lda     .src_hi,x
        sta     <_bp+1
        ldy     .src_bank,x
        call    map_bp_to_mpr34

        lda     #<((CHR_GAME+9)*16)
        sta     <_di
        lda     #>((CHR_GAME+9)*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ldx     room20_33_decor_index
        lda     .pages,x
        tax
        beq     .tail_setup
.page:
        cly
.copy_page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .copy_page
        inc     <_bp+1
        dex
        bne     .page

.tail_setup:
        ldx     room20_33_decor_index
        lda     .tail_words,x
        tax
        beq     .done
        cly
.tail:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        dex
        bne     .tail

.done:
        pla
        tam4
        pla
        tam3
        plp
        leave

.room_ids:
        db $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2b,$2d,$2e,$30,$31,$32,$33
.src_lo:
        db <room20_decor_patterns,<room21_decor_patterns,<room22_decor_patterns,<room23_decor_patterns
        db <room24_decor_patterns,<room25_decor_patterns,<room26_decor_patterns,<room27_decor_patterns
        db <room28_decor_patterns,<room29_decor_patterns,<room2b_decor_patterns,<room2d_decor_patterns
        db <room2e_decor_patterns,<room30_decor_patterns,<room31_decor_patterns,<room32_decor_patterns
        db <room33_decor_patterns
.src_hi:
        db >room20_decor_patterns,>room21_decor_patterns,>room22_decor_patterns,>room23_decor_patterns
        db >room24_decor_patterns,>room25_decor_patterns,>room26_decor_patterns,>room27_decor_patterns
        db >room28_decor_patterns,>room29_decor_patterns,>room2b_decor_patterns,>room2d_decor_patterns
        db >room2e_decor_patterns,>room30_decor_patterns,>room31_decor_patterns,>room32_decor_patterns
        db >room33_decor_patterns
.src_bank:
        db BANK(room20_decor_patterns),BANK(room21_decor_patterns),BANK(room22_decor_patterns),BANK(room23_decor_patterns)
        db BANK(room24_decor_patterns),BANK(room25_decor_patterns),BANK(room26_decor_patterns),BANK(room27_decor_patterns)
        db BANK(room28_decor_patterns),BANK(room29_decor_patterns),BANK(room2b_decor_patterns),BANK(room2d_decor_patterns)
        db BANK(room2e_decor_patterns),BANK(room30_decor_patterns),BANK(room31_decor_patterns),BANK(room32_decor_patterns)
        db BANK(room33_decor_patterns)

; Character counts:
; R20=34 R21=4 R22=4 R23=50 R24=22 R25=36 R26=44 R27=45 R28=22
; R29=59 R2B=30 R2D=36 R2E=35 R30=9 R31=54 R32=49 R33=51.
.pages:
        db 4,0,0,6,2,4,5,5,2,7,3,4,4,1,6,6,6
.tail_words:
        db 32,64,64,32,96,64,64,80,96,48,96,64,48,16,96,16,48
.endp

; Extended rooms use compressed 36x20 BAT streams in ROM. Keep the depacker
; next to the late-room loader so it is available before room050c_loader.asm.
        include "room_bat_rle.asm"
