; Exact Room $0B decor upload: 25 chars generated by tools/room0b_decor.py.
CHR_ROOM0B_DECOR = CHR_GAME + 9

.code
room0b_upload_decor:
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     #<room0b_decor_patterns
        sta     <_bp
        lda     #>room0b_decor_patterns
        sta     <_bp+1
        ldy     #BANK(room0b_decor_patterns)
        call    map_bp_to_mpr34

        lda     #<(CHR_ROOM0B_DECOR*16)
        sta     <_di
        lda     #>(CHR_ROOM0B_DECOR*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ; 25 chars * 32 bytes = 800 bytes = 3 pages + 32 bytes.
        ldx     #3
.page:
        cly
.copy_page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .copy_page
        inc     <_bp+1
        dex
        bne     .page

        cly
        ldx     #16
.tail:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        dex
        bne     .tail

        pla
        tam4
        pla
        tam3
        plp
        rts
