; Bank-safe decor upload for the seven Rooms $10-$1F that contain original
; Decor.room_list objects. BAT placement is generated by rooms10_1f_decor.py.

.bss
room10_1f_decor_index: ds 1

.code
.proc room10_1f_upload_decor
        lda     <world_pending_room
        ldx     #0
.find:
        cmp     .room_ids,x
        beq     .found
        inx
        cpx     #7
        bne     .find
        leave

.found:
        stx     room10_1f_decor_index
        php
        sei
        tma3
        pha
        tma4
        pha

        lda     .src_lo,x
        sta     <_bp
        lda     .src_hi,x
        sta     <_bp+1
        ldy     .src_bank,x
        call    map_bp_to_mpr34

        lda     #<((CHR_GAME+9)*16)
        sta     <_di
        lda     #>((CHR_GAME+9)*16)
        sta     <_di+1
        call    vdc_di_to_mawr

        ldx     room10_1f_decor_index
        lda     .pages,x
        tax
        beq     .tail_setup
.page:
        cly
.copy_page:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        bne     .copy_page
        inc     <_bp+1
        dex
        bne     .page

.tail_setup:
        ldx     room10_1f_decor_index
        lda     .tail_words,x
        tax
        beq     .done
        cly
.tail:
        lda     [_bp],y
        sta     VDC_DL
        iny
        lda     [_bp],y
        sta     VDC_DH
        iny
        dex
        bne     .tail

.done:
        pla
        tam4
        pla
        tam3
        plp
        leave

.room_ids:
        db $10,$11,$12,$13,$1d,$1e,$1f
.src_lo:
        db <room10_decor_patterns,<room11_decor_patterns,<room12_decor_patterns,<room13_decor_patterns,<room1d_decor_patterns,<room1e_decor_patterns,<room1f_decor_patterns
.src_hi:
        db >room10_decor_patterns,>room11_decor_patterns,>room12_decor_patterns,>room13_decor_patterns,>room1d_decor_patterns,>room1e_decor_patterns,>room1f_decor_patterns
.src_bank:
        db BANK(room10_decor_patterns),BANK(room11_decor_patterns),BANK(room12_decor_patterns),BANK(room13_decor_patterns),BANK(room1d_decor_patterns),BANK(room1e_decor_patterns),BANK(room1f_decor_patterns)
; Character counts: 23,48,33,6,51,26,56. Every char is 32 bytes.
.pages:
        db 2,6,4,0,6,3,7
.tail_words:
        db 112,0,16,96,48,32,0
.endp
